name: Push installation image 

on: 
  workflow_dispatch:
  release:
    types: [published, created, edited]

jobs:
  windows-install-node:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Download node.js version from nodejs.org
        run: |
          curl -o ./nodejs-win.zip --create-dirs https://nodejs.org/dist/v18.12.1/node-v18.12.1-win-x64.zip      
          mkdir nodejs-win && tar -xzf nodejs-win.zip -C nodejs-win --strip-components=1 && rm ./nodejs-win.zip

      - name: Check out sub-directory and copy all files
        run: |
          mkdir purple-hats
          cd purple-hats
          robocopy ${{github.workspace}} ./ /COPYALL /E /XD purple-hats

      - name: Install Node Modules for Windows
        run: npm i fsevents@latest -f --save-optional && npm ci 
        working-directory: purple-hats
              
      - name: Grant execute permissions for user
        run: chmod ugo+rwx ./scripts/hats_shell.cmd ./scripts/hats_shell_ps.ps1
        working-directory: purple-hats

      - name: Copy scripts to parent directory
        run: |
          cd
          cp ./*  ${{github.workspace}}
        working-directory: purple-hats/scripts

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows-artifact
          path: ${{ github.workspace }}

  mac-security-prompt-install-node:
    runs-on: macos-latest  

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Download node.js version from nodejs.org
        run: |         
          curl -o ./nodejs-mac-arm64.tar.gz --create-dirs https://nodejs.org/dist/v18.12.1/node-v18.12.1-darwin-arm64.tar.gz      
          mkdir nodejs-mac-arm64 && tar -xzf nodejs-mac-arm64.tar.gz -C nodejs-mac-arm64 --strip-components=1 && rm ./nodejs-mac-arm64.tar.gz
          curl -o ./nodejs-mac-x64.tar.gz --create-dirs https://nodejs.org/dist/v18.12.1/node-v18.12.1-darwin-x64.tar.gz     
          mkdir nodejs-mac-x64 && tar -xzf nodejs-mac-x64.tar.gz -C nodejs-mac-x64 --strip-components=1 && rm ./nodejs-mac-x64.tar.gz
      
      - name: Check out sub-directory and copy all files
        run: mkdir purple-hats && rsync -av --progress ./* /purple-hats --exclude purple-hats

      - name: Install Node Modules for Mac0S
        run: npm ci 
        working-directory: purple-hats

      - name: Grant execute permissions for user
        run: chmod ugo+rwx ./scripts/hats_shell.command ./scripts/hats_shell.sh ./scripts/purple_hats_install.command
        working-directory: purple-hats

      - name: Copy scripts to parent directory
        run: |
          pwd
          cp ./*  ../../
        working-directory: purple-hats/scripts
      
      - name: Zip entire Purple Hats folder
        run: |
          if [[ $(uname -m) == 'arm64' ]]; then        
            zip -r purple-hats-portable-mac-arm64.zip purple-hats hats_shell.command hats_shell.sh purple_hats_install.command nodejs-mac-arm64
          else
            zip -r purple-hats-portable-mac-x64.zip purple-hats hats_shell.command hats_shell.sh purple_hats_install.command nodejs-mac-x64
          fi

      - name: Upload MAC artifact
        uses: actions/upload-artifact@v1
        with:
          name: mac-artifact
          path: ${{ github.workspace }}
