name: Push installation image 

on: 
  workflow_dispatch:
  release:
    types: [published, created, edited]

jobs:
  windows-install-node:
    runs-on: windows-latest

    steps:
      - name: Download node.js version from nodejs.org
        run: |
          curl -o ./nodejs-win.zip --create-dirs https://nodejs.org/dist/v18.12.1/node-v18.12.1-win-x64.zip      
          mkdir nodejs-win && tar -xzf nodejs-win.zip -C nodejs-win --strip-components=1 && rm ./nodejs-win.zip

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: purple-hats

      - name: Install Node Modules for Windows
        run: |
          cd
          npm i fsevents@latest -f --save-optional && npm ci 
        working-directory: purple-hats
              
      - name: Copy scripts to parent directory
        run: |
          cd
          cp ${{github.workspace}}/purple-hats/scripts/*  ${{github.workspace}}

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows-artifact
          path: ${{ github.workspace }}

  mac-security-prompt-install-node:
    runs-on: macos-latest  

    steps:
      - name: Download node.js version from nodejs.org
        run: |         
          curl -o ./nodejs-mac-arm64.tar.gz --create-dirs https://nodejs.org/dist/v18.12.1/node-v18.12.1-darwin-arm64.tar.gz      
          mkdir nodejs-mac-arm64 && tar -xzf nodejs-mac-arm64.tar.gz -C nodejs-mac-arm64 --strip-components=1 && rm ./nodejs-mac-arm64.tar.gz
          curl -o ./nodejs-mac-x64.tar.gz --create-dirs https://nodejs.org/dist/v18.12.1/node-v18.12.1-darwin-x64.tar.gz     
          mkdir nodejs-mac-x64 && tar -xzf nodejs-mac-x64.tar.gz -C nodejs-mac-x64 --strip-components=1 && rm ./nodejs-mac-x64.tar.gz

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: purple-hats

      - name: Install Node Modules for Mac0S
        run: npm ci 
        working-directory: purple-hats

      - name: Grant execute permissions for user
        run: chmod ugo+rwx ./scripts/hats_shell.command ./scripts/hats_shell.sh ./scripts/purple_hats_install.command
        working-directory: purple-hats

      - name: Copy scripts to parent directory
        run: |
          pwd
          cp ./purple-hats/scripts/*  ${{ github.workspace }}
      
      - name: Zip entire Purple Hats folder
        run: |
          if [[ $(uname -m) == 'arm64' ]]; then        
            zip purple-hats-portable-mac-arm64.zip -r . --exclude 'hats_shell_ps.ps1' 'hats_shell.cmd'
          else
            zip purple-hats-portable-mac-x64.zip -r . --exclude 'hats_shell_ps.ps1' 'hats_shell.cmd'
          fi

      - name: Upload MAC artifact
        uses: actions/upload-artifact@v1
        with:
          name: mac-artifact
          path: ${{ github.workspace }}
