name: Push installation image 

on: 
  workflow_dispatch:
  release:
    types: [published, created, edited]

jobs:
  windows-install-node:
    runs-on: windows-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Download node.js version from nodejs.org
        run: |
          curl -o ./nodejs-win.zip --create-dirs https://nodejs.org/dist/v18.12.1/node-v18.12.1-win-x64.zip      
          mkdir nodejs-win && tar -xzf nodejs-win.zip -C nodejs-win --strip-components=1 && rm ./nodejs-win.zip
      
      - name: Install Node Modules
          run: npm i fsevents@latest -f --save-optional && npm ci 
          working-directory: purple-hats

      - name: Download Windows zip file 
        uses: actions/upload-artifact@v1
        with:
          name: windows-artifact
          path: ${{ github.workspace }}

  mac-security-prompt-install-node:
    runs-on: macos-latest  

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Download correct node.js version from nodejs.org
        run: |         
          if [[ $(uname -m) == 'arm64' ]]; then
            curl -o ./nodejs-mac-arm64.tar.gz --create-dirs https://nodejs.org/dist/v18.12.1/node-v18.12.1-darwin-arm64.tar.gz      
            mkdir nodejs-mac-arm64 && tar -xzf nodejs-mac-arm64.tar.gz -C nodejs-mac-arm64 --strip-components=1 && rm ./nodejs-mac-arm64.tar.gz
          else
            curl -o ./nodejs-mac-x64.tar.gz --create-dirs https://nodejs.org/dist/v18.12.1/node-v18.12.1-darwin-x64.tar.gz     
            mkdir nodejs-mac-x64 && tar -xzf nodejs-mac-x64.tar.gz -C nodejs-mac-x64 --strip-components=1 && rm ./nodejs-mac-x64.tar.gz
          fi

      - name: Install Node Modules
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: |
          cd purple-hats
          npm ci 

      - name: Grant execute permissions for user
        run: |
          chmod ugo+rwx ./scripts/hats_shell.command ./scripts/hats_shell.sh
          export PATH_TO_BETTER_SQLITE3="./purple-hats/node_modules/better-sqlite3-with-prebuilds/build/Release/better_sqlite3.node"
          echo "path to better_sqlite3: $PATH_TO_BETTER_SQLITE3"

          xattr -d com.apple.quarantine $PATH_TO_BETTER_SQLITE3
        continue-on-error: true

      - name: Download zip file Mac
        uses: actions/upload-artifact@v1
        with:
          name: mac-artifact
          path: ${{ github.workspace }}
