name: Push Windows installation image 

on: 
  workflow_dispatch:
  release:
    types: [published, created, edited]

jobs:
  windows-install-node:
    runs-on: windows-latest

    steps:
      - name: Download node.js version from nodejs.org
        run: |
          curl -o ./nodejs-win.zip --create-dirs https://nodejs.org/dist/v18.12.1/node-v18.12.1-win-x64.zip      
          mkdir nodejs-win && tar -xzf nodejs-win.zip -C nodejs-win --strip-components=1 && rm ./nodejs-win.zip

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          path: purple-hats

      - name: Copy scripts to parent directory
        run: |
          cp ${{github.workspace}}/purple-hats/scripts/*.ps1 ${{github.workspace}}
          cp ${{github.workspace}}/purple-hats/scripts/*.cmd ${{github.workspace}}      
          rd -r ${{github.workspace}}/purple-hats/scripts

      - name: Run hats_shell._ps.ps1
        shell: pwsh
        run: |
          Set-ExecutionPolicy Unrestricted -Scope CurrentUser
          .\hats_shell_ps.ps1
          mkdir -p ${{github.workspace}}/purple-hats/node_modules
          npm i --prefix ${{github.workspace}}/purple-hats fsevents@latest -f --save-optional 

      - name: Install Node Modules for Windows
        run: |
          cd purple-hats
          dir
          npm i fsevents@latest -f --save-optional 

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows-artifact
          path: ${{ github.workspace }}